name: Image-Transfer
on: workflow_dispatch # 手动触发

jobs:
  download-and-pack:
    runs-on: ubuntu-latest
    steps:
      - name: Pull and Save Image
        run: |
          # 1. 从 GitHub 内部极速拉取镜像
          docker pull ghcr.io/immich-app/immich-machine-learning:release
          # 2. 打包成 tar 文件
          docker save ghcr.io/immich-app/immich-machine-learning:release -o immich-ml.tar
          # 3. 为了下载更快，压缩一下
          tar -czvf immich-ml.tar.gz immich-ml.tar
      - name: Upload to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: immich-package # 这是下载时的文件名
          path: immich-ml.tar.gz
          retention-days: 1 # 下完就删，省空间
